name = "article-reader-app"
main = "worker.ts"
compatibility_date = "2026-07-11"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "tech-news.jocelinho.com", custom_domain = true },
  { pattern = "article.jocelinho.com", custom_domain = true }
]

[assets]
directory = "./out"
binding = "ASSETS"
run_worker_first = true
html_handling = "auto-trailing-slash"
not_found_handling = "404-page"

[[d1_databases]]
binding = "DB"
database_name = "article-reader-db"
database_id = "686d8e26-ad14-47a1-b4ad-9710fe360d48"
